/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.example.utilities.StringUtils

import org.apache.commons.text.WordUtils

import org.example.app.FuncsUteis

fun main() {

    FuncsUteis.databaseConnection()//Conecta ao Banco de Dados

    FuncsUteis.selectUsuarioEspecifico("nome")
}
